version: '3'

services:
# ### workspace ################################################
#     workspace:
#         image: wordpress:${WORDPRESS_TAG}
#         environment:
#             - WORDPRESS_DB_HOST=mysql
#             - WORDPRESS_DB_USER=${MYSQL_USER}
#             - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
#             - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
#         volumes:
#             - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
#         depends_on:
#             - mysql
    workspace:
        build:
            context: ./workspace
            args:
                - PHP_VERSION=${PHP_VERSION}
                - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG}
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        depends_on:
            - mysql

### NGINX server ################################################
    nginx:
        build:
            context: ./nginx
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - workspace

### MySQL ################################################
    mysql:
        build:
            context: ./mysql
            args:
            - MYSQL_VERSION=${MYSQL_VERSION}
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=${WORKSPACE_TIMEZONE}
        volumes:
            - ${DATA_PATH_HOST}/${APP_NAME}/mysql:/var/lib/mysql
            - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
        ports:
            - "${MYSQL_PORT}:3306"